import { VagaRecord, PessoaRecord, PontoRecord } from '../types';

export const INITIAL_VAGAS_DATA: VagaRecord[] = [
  {
    id: 'vg-01',
    codigoVaga: 'VAG-2026-081',
    cargo: 'Operador de Empilhadeira',
    filial: 'CUIABÁ - MT',
    dataSolicitacao: '2026-07-02',
    dataFechamento: undefined,
    status: 'Aberta',
    motivo: 'Substituição',
    pessoaSustituida: 'Marcos Vinicius de Souza',
    slaDias: 47,
    slaMeta: 25,
    solicitante: 'Gerson Lima (Coord. Logística)',
    recrutador: 'Camila Santos',
    nivelPrioridade: 'Alta',
  },
  {
    id: 'vg-02',
    codigoVaga: 'VAG-2026-084',
    cargo: 'Operador de Empilhadeira',
    filial: 'CUIABÁ - MT',
    dataSolicitacao: '2026-07-10',
    dataFechamento: undefined,
    status: 'Aberta',
    motivo: 'Substituição',
    pessoaSustituida: 'Ronaldo Peixoto de Abreu',
    slaDias: 39,
    slaMeta: 25,
    solicitante: 'Gerson Lima (Coord. Logística)',
    recrutador: 'Camila Santos',
    nivelPrioridade: 'Alta',
  },
  {
    id: 'vg-03',
    codigoVaga: 'VAG-2026-088',
    cargo: 'Motorista Carreteiro',
    filial: 'VÁRZEA GRANDE - MT',
    dataSolicitacao: '2026-07-05',
    dataFechamento: undefined,
    status: 'Aberta',
    motivo: 'Substituição',
    pessoaSustituida: 'Luciano Ribeiro Mendes',
    slaDias: 44,
    slaMeta: 30,
    solicitante: 'Eduardo Guimarães (Gerente Frotas)',
    recrutador: 'Lucas Fagundes',
    nivelPrioridade: 'Alta',
  },
  {
    id: 'vg-04',
    codigoVaga: 'VAG-2026-092',
    cargo: 'Auxiliar de Operações Logísticas',
    filial: 'CUIABÁ - MT',
    dataSolicitacao: '2026-07-18',
    dataFechamento: undefined,
    status: 'Aberta',
    motivo: 'Substituição',
    pessoaSustituida: 'Juliana Paes Ferreira',
    slaDias: 31,
    slaMeta: 20,
    solicitante: 'Tatiane Ramos (Supervisora Armazém)',
    recrutador: 'Fernanda Nogueira',
    nivelPrioridade: 'Alta',
  },
  {
    id: 'vg-05',
    codigoVaga: 'VAG-2026-095',
    cargo: 'Conferente de Carga',
    filial: 'VÁRZEA GRANDE - MT',
    dataSolicitacao: '2026-07-22',
    dataFechamento: undefined,
    status: 'Aberta',
    motivo: 'Substituição',
    pessoaSustituida: 'Clayton Aparecido Lima',
    slaDias: 27,
    slaMeta: 20,
    solicitante: 'Márcio Teles (Superv. Expedição)',
    recrutador: 'Fernanda Nogueira',
    nivelPrioridade: 'Alta',
  },
  {
    id: 'vg-06',
    codigoVaga: 'VAG-2026-099',
    cargo: 'Técnico de Manutenção Mecânica',
    filial: 'CUIABÁ - MT',
    dataSolicitacao: '2026-07-15',
    dataFechamento: undefined,
    status: 'Em Andamento',
    motivo: 'Aumento de Quadro',
    slaDias: 34,
    slaMeta: 30,
    solicitante: 'Roberto Vasconcelos (Manutenção)',
    recrutador: 'Camila Santos',
    nivelPrioridade: 'Média',
  },
  {
    id: 'vg-07',
    codigoVaga: 'VAG-2026-102',
    cargo: 'Auxiliar de Operações Logísticas',
    filial: 'VÁRZEA GRANDE - MT',
    dataSolicitacao: '2026-07-28',
    dataFechamento: undefined,
    status: 'Aberta',
    motivo: 'Substituição',
    pessoaSustituida: 'Everton Silveira Dias',
    slaDias: 21,
    slaMeta: 20,
    solicitante: 'Tatiane Ramos (Supervisora Armazém)',
    recrutador: 'Fernanda Nogueira',
    nivelPrioridade: 'Média',
  },
  {
    id: 'vg-08',
    codigoVaga: 'VAG-2026-070',
    cargo: 'Assistente Administrativo de Frota',
    filial: 'CUIABÁ - MT',
    dataSolicitacao: '2026-06-12',
    dataFechamento: '2026-07-04',
    status: 'Fechada',
    motivo: 'Substituição',
    slaDias: 22,
    slaMeta: 25,
    solicitante: 'Eduardo Guimarães',
    recrutador: 'Camila Santos',
    nivelPrioridade: 'Normal',
  },
  {
    id: 'vg-09',
    codigoVaga: 'VAG-2026-073',
    cargo: 'Motorista Carreteiro',
    filial: 'CUIABÁ - MT',
    dataSolicitacao: '2026-06-15',
    dataFechamento: '2026-07-16',
    status: 'Fechada',
    motivo: 'Aumento de Quadro',
    slaDias: 31,
    slaMeta: 30,
    solicitante: 'Eduardo Guimarães',
    recrutador: 'Lucas Fagundes',
    nivelPrioridade: 'Alta',
  },
  {
    id: 'vg-10',
    codigoVaga: 'VAG-2026-075',
    cargo: 'Auxiliar de Operações Logísticas',
    filial: 'CUIABÁ - MT',
    dataSolicitacao: '2026-06-20',
    dataFechamento: '2026-07-08',
    status: 'Fechada',
    motivo: 'Substituição',
    slaDias: 18,
    slaMeta: 20,
    solicitante: 'Cláudio Duarte',
    recrutador: 'Lucas Fagundes',
    nivelPrioridade: 'Normal',
  },
  {
    id: 'vg-11',
    codigoVaga: 'VAG-2026-105',
    cargo: 'Motorista Carreteiro',
    filial: 'VÁRZEA GRANDE - MT',
    dataSolicitacao: '2026-07-29',
    dataFechamento: undefined,
    status: 'Aberta',
    motivo: 'Aumento de Quadro',
    slaDias: 20,
    slaMeta: 30,
    solicitante: 'Cláudio Duarte',
    recrutador: 'Lucas Fagundes',
    nivelPrioridade: 'Média',
  },
  {
    id: 'vg-12',
    codigoVaga: 'VAG-2026-108',
    cargo: 'Assistente de Faturamento',
    filial: 'CUIABÁ - MT',
    dataSolicitacao: '2026-07-14',
    dataFechamento: '2026-08-05',
    status: 'Fechada',
    motivo: 'Substituição',
    slaDias: 22,
    slaMeta: 25,
    solicitante: 'Valéria Monteiro',
    recrutador: 'Camila Santos',
    nivelPrioridade: 'Normal',
  },
  {
    id: 'vg-13',
    codigoVaga: 'VAG-2026-110',
    cargo: 'Vendedor Externo',
    filial: 'VÁRZEA GRANDE - MT',
    dataSolicitacao: '2026-07-10',
    dataFechamento: undefined,
    status: 'Aberta',
    motivo: 'Aumento de Quadro',
    slaDias: 39,
    slaMeta: 30,
    solicitante: 'Renato Farias',
    recrutador: 'Fernanda Nogueira',
    nivelPrioridade: 'Média',
  },
  {
    id: 'vg-14',
    codigoVaga: 'VAG-2026-112',
    cargo: 'Operador de Empilhadeira',
    filial: 'VÁRZEA GRANDE - MT',
    dataSolicitacao: '2026-07-20',
    dataFechamento: undefined,
    status: 'Aberta',
    motivo: 'Substituição',
    pessoaSustituida: 'Daniel Barreto Costa',
    slaDias: 29,
    slaMeta: 25,
    solicitante: 'Márcio Teles',
    recrutador: 'Fernanda Nogueira',
    nivelPrioridade: 'Alta',
  },
  {
    id: 'vg-15',
    codigoVaga: 'VAG-2026-060',
    cargo: 'Auxiliar de Operações Logísticas',
    filial: 'CUIABÁ - MT',
    dataSolicitacao: '2026-05-10',
    dataFechamento: '2026-05-29',
    status: 'Fechada',
    motivo: 'Substituição',
    slaDias: 19,
    slaMeta: 20,
    solicitante: 'Tatiane Ramos',
    recrutador: 'Camila Santos',
    nivelPrioridade: 'Normal',
  },
  {
    id: 'vg-16',
    codigoVaga: 'VAG-2026-062',
    cargo: 'Conferente de Carga',
    filial: 'CUIABÁ - MT',
    dataSolicitacao: '2026-05-15',
    dataFechamento: '2026-06-08',
    status: 'Fechada',
    motivo: 'Substituição',
    slaDias: 24,
    slaMeta: 20,
    solicitante: 'Gerson Lima',
    recrutador: 'Fernanda Nogueira',
    nivelPrioridade: 'Normal',
  }
];

export const INITIAL_PESSOAS_DATA: PessoaRecord[] = [
  {
    id: 'pes-4041',
    matricula: '5050',
    matriculaDolp: '5050',
    matriculaContratante: 'BR0038779515',
    empresa: 'DOLP ENGENHARIA LTDA - MT',
    nome: 'ANDERSON DO CARMO SANTOS',
    cargo: 'ELETRICISTA DE REDES DE DISTRIBUIÇÃO',
    tipoFuncao: 'OPERACIONAL',
    filial: 'CUIABÁ - MT',
    departamento: 'OPERACIONAL - CUIABA',
    dataNascimento: '1989-07-10',
    idade: 37,
    naturalidade: 'ALAGOINHAS',
    estadoCivil: 'Solteiro(a)',
    cpf: '038.779.515-46',
    rg: '03877951546',
    orgaoExpeditor: 'SSPBA',
    situacao: 'Em Atividade',
    status: 'Ativo',
    celular: '75999691951',
    membroCipa: 'NÃO',
    ancora: 'SIM',
    dataAdmissao: '2026-05-25',
    tempoDeCasaDias: 85,
    tempoDeCasaMeses: 2.8,
    faixaTempoCasa: '< 90 dias (Precoce)',
    gestor: 'DIEFFERSON VITORINO DE MACEDO',
  },
  {
    id: 'pes-2226',
    matricula: '2601',
    matriculaDolp: '2601',
    matriculaContratante: 'BR001144661',
    empresa: 'DOLP ENGENHARIA LTDA - MT',
    nome: 'ADEILSON BELMIRO',
    cargo: 'ELETRICISTA DE REDES DE DISTRIBUIÇÃO',
    tipoFuncao: 'OPERACIONAL',
    filial: 'CUIABÁ - MT',
    departamento: 'OPERACIONAL - CUIABA',
    dataNascimento: '1983-05-22',
    idade: 43,
    naturalidade: 'RIO BRANCO',
    estadoCivil: 'Casado(a)',
    cpf: '001.144.661-73',
    rg: '14954419',
    orgaoExpeditor: 'SSP',
    situacao: 'Afastado',
    status: 'Ativo',
    celular: '65992535341',
    membroCipa: 'NÃO',
    ancora: 'NÃO',
    dataAdmissao: '2024-09-05',
    tempoDeCasaDias: 712,
    tempoDeCasaMeses: 23.4,
    faixaTempoCasa: '1 - 2 anos',
    gestor: 'ALINE CYNTHIA BARBOSA',
  },
  {
    id: 'pes-1830',
    matricula: '2256',
    matriculaDolp: '2256',
    matriculaContratante: 'BR000908901',
    empresa: 'DOLP ENGENHARIA LTDA - MT',
    nome: 'ADELSO PEREIRA MARQUES DE ARRUDA',
    cargo: 'ELETRICISTA DE REDES DE DISTRIBUIÇÃO',
    tipoFuncao: 'OPERACIONAL',
    filial: 'CUIABÁ - MT',
    departamento: 'OPERACIONAL - CUIABA',
    dataNascimento: '1985-02-15',
    idade: 41,
    naturalidade: 'CUIABA',
    estadoCivil: 'Solteiro(a)',
    cpf: '000.908.901-24',
    rg: '14573466',
    orgaoExpeditor: 'SSP',
    situacao: 'Desligado',
    status: 'Desligado',
    celular: '65993384488',
    membroCipa: 'NÃO',
    ancora: 'NÃO',
    dataAdmissao: '2024-06-13',
    dataDemissao: '2024-12-13',
    tempoDeCasaDias: 183,
    tempoDeCasaMeses: 6.0,
    faixaTempoCasa: '180 dias - 1 ano',
    tipoDesligamento: 'Voluntário (Pedido)',
    motivoSaida: 'Proposta concorrente no setor elétrico',
    gestor: 'DIEFFERSON VITORINO DE MACEDO',
  },
  {
    id: 'pes-2139',
    matricula: '2539',
    matriculaDolp: '2539',
    matriculaContratante: 'BR959130761',
    empresa: 'DOLP ENGENHARIA LTDA - MT',
    nome: 'ADEMILSON DE LIMA',
    cargo: 'ELETRICISTA DE REDES DE DISTRIBUIÇÃO',
    tipoFuncao: 'OPERACIONAL',
    filial: 'CUIABÁ - MT',
    departamento: 'OPERACIONAL - CUIABA',
    dataNascimento: '1977-08-15',
    idade: 49,
    naturalidade: 'CUIABA',
    estadoCivil: 'Solteiro(a)',
    cpf: '959.130.761-68',
    rg: '10110879',
    orgaoExpeditor: 'SSP',
    situacao: 'Desligado',
    status: 'Desligado',
    dataAdmissao: '2024-08-16',
    dataDemissao: '2025-11-19',
    tempoDeCasaDias: 460,
    tempoDeCasaMeses: 15.1,
    faixaTempoCasa: '1 - 2 anos',
    tipoDesligamento: 'Involuntário (Empresa)',
    motivoSaida: 'Reestruturação de quadro operacional',
    gestor: 'JOSE DANIEL SANTOS NASCIMENTO',
  },
  {
    id: 'pes-3230',
    matricula: '3470',
    matriculaDolp: '3470',
    matriculaContratante: 'BR0700211551',
    empresa: 'DOLP ENGENHARIA LTDA - MT',
    nome: 'ADEMILSON JOSE MENDES RODRIGUES',
    cargo: 'ELETRICISTA DE REDES DE DISTRIBUIÇÃO',
    tipoFuncao: 'OPERACIONAL',
    filial: 'CUIABÁ - MT',
    departamento: 'OPERACIONAL - CUIABA',
    dataNascimento: '1981-11-14',
    idade: 44,
    naturalidade: 'ROSARIO OESTE',
    estadoCivil: 'Solteiro(a)',
    cpf: '700.211.551-00',
    rg: '12538108',
    orgaoExpeditor: 'SSP',
    situacao: 'Em Atividade',
    status: 'Ativo',
    celular: '65993249449',
    membroCipa: 'NÃO',
    ancora: 'NÃO',
    dataAdmissao: '2025-03-24',
    tempoDeCasaDias: 512,
    tempoDeCasaMeses: 16.8,
    faixaTempoCasa: '1 - 2 anos',
    gestor: 'JUCELMO JOSE DA SILVA SANTOS',
  },
  {
    id: 'pes-4010',
    matricula: '5024',
    matriculaDolp: '5024',
    matriculaContratante: 'BR0710162281',
    empresa: 'DOLP ENGENHARIA LTDA - MT',
    nome: 'ADEMILSON RAMOS SILVA',
    cargo: 'ASSISTENTE OPERACIONAL',
    tipoFuncao: 'ADMINISTRATIVO',
    filial: 'CUIABÁ - MT',
    departamento: 'ADMINISTRATIVO - CUIABA',
    dataNascimento: '1982-12-26',
    idade: 43,
    naturalidade: 'ROSARIO OESTE',
    estadoCivil: 'Casado(a)',
    cpf: '710.162.281-04',
    rg: '649592',
    orgaoExpeditor: 'SSP',
    situacao: 'Em Atividade',
    status: 'Ativo',
    celular: '65992805298',
    membroCipa: 'NÃO',
    ancora: 'SIM',
    dataAdmissao: '2026-05-19',
    tempoDeCasaDias: 91,
    tempoDeCasaMeses: 3.0,
    faixaTempoCasa: '90 - 180 dias',
    gestor: 'ALINE CYNTHIA BARBOSA',
  },
  {
    id: 'pes-1949',
    matricula: '2377',
    matriculaDolp: '2377',
    matriculaContratante: 'BR004489141',
    empresa: 'DOLP ENGENHARIA LTDA - MT',
    nome: 'ADEMILSON SOUZA CORTEZ',
    cargo: 'ELETRICISTA DE REDES DE DISTRIBUIÇÃO',
    tipoFuncao: 'OPERACIONAL',
    filial: 'CUIABÁ - MT',
    departamento: 'OPERACIONAL - CUIABA',
    dataNascimento: '1983-11-01',
    idade: 42,
    naturalidade: 'POCONE',
    estadoCivil: 'Solteiro(a)',
    cpf: '004.489.141-58',
    rg: '15028240',
    orgaoExpeditor: 'SSP',
    situacao: 'Desligado',
    status: 'Desligado',
    celular: '65996991869',
    membroCipa: 'NÃO',
    ancora: 'NÃO',
    dataAdmissao: '2024-07-09',
    dataDemissao: '2025-10-31',
    tempoDeCasaDias: 479,
    tempoDeCasaMeses: 15.7,
    faixaTempoCasa: '1 - 2 anos',
    tipoDesligamento: 'Voluntário (Pedido)',
    motivoSaida: 'Mudança de cidade e concorrência',
    gestor: 'MARCOS ANDREY BORGES DA SILVA',
  },
  {
    id: 'pes-2021',
    matricula: '2447',
    matriculaDolp: '2447',
    matriculaContratante: 'BR568087471',
    empresa: 'DOLP ENGENHARIA LTDA - MT',
    nome: 'ADENOR DE SOUZA NERES',
    cargo: 'ELETRICISTA DE REDES DE DISTRIBUIÇÃO',
    tipoFuncao: 'OPERACIONAL',
    filial: 'CUIABÁ - MT',
    departamento: 'OPERACIONAL - CUIABA',
    dataNascimento: '1971-10-12',
    idade: 54,
    naturalidade: 'BARRA DO GARCAS',
    estadoCivil: 'Solteiro(a)',
    cpf: '568.087.471-72',
    rg: '816576',
    orgaoExpeditor: 'SSP',
    situacao: 'Desligado',
    status: 'Desligado',
    celular: '65992061289',
    membroCipa: 'NÃO',
    ancora: 'NÃO',
    dataAdmissao: '2024-07-30',
    dataDemissao: '2025-07-15',
    tempoDeCasaDias: 350,
    tempoDeCasaMeses: 11.5,
    faixaTempoCasa: '180 dias - 1 ano',
    tipoDesligamento: 'Acordo Mútuo',
    motivoSaida: 'Aposentadoria / Transição de carreira',
    gestor: 'AILTON VICENTE DE LIMA',
  },
  {
    id: 'pes-1851',
    matricula: '2277',
    matriculaDolp: '2277',
    matriculaContratante: 'BR000841801',
    empresa: 'DOLP ENGENHARIA LTDA - MT',
    nome: 'ADILSON CARVALHO DE CAMPOS',
    cargo: 'ELETRICISTA DE REDES DE DISTRIBUIÇÃO',
    tipoFuncao: 'OPERACIONAL',
    filial: 'VÁRZEA GRANDE - MT',
    departamento: 'OPERACIONAL - VARZEA GRANDE',
    dataNascimento: '1984-08-14',
    idade: 42,
    naturalidade: 'CUIABA',
    estadoCivil: 'União Estável',
    cpf: '000.841.801-29',
    rg: '13373307',
    orgaoExpeditor: 'SSP',
    situacao: 'Desligado',
    status: 'Desligado',
    celular: '65993471852',
    membroCipa: 'NÃO',
    ancora: 'NÃO',
    dataAdmissao: '2024-06-19',
    dataDemissao: '2026-07-22',
    tempoDeCasaDias: 763,
    tempoDeCasaMeses: 25.1,
    faixaTempoCasa: '> 2 anos',
    tipoDesligamento: 'Voluntário (Pedido)',
    motivoSaida: 'Sobrecarga de escala e concorrência',
    gestor: 'ALINE CYNTHIA BARBOSA',
  },
  {
    id: 'pes-1833',
    matricula: '2259',
    matriculaDolp: '2259',
    matriculaContratante: 'BR979768731',
    empresa: 'DOLP ENGENHARIA LTDA - MT',
    nome: 'ADILSON CEZAR GUSMAO SANTANA',
    cargo: 'ELETRICISTA DE REDES DE DISTRIBUIÇÃO',
    tipoFuncao: 'OPERACIONAL',
    filial: 'CUIABÁ - MT',
    departamento: 'OPERACIONAL - CUIABA',
    dataNascimento: '1979-08-30',
    idade: 46,
    naturalidade: 'CUIABA',
    estadoCivil: 'Solteiro(a)',
    cpf: '979.768.731-72',
    rg: '13189638',
    orgaoExpeditor: 'SESP',
    situacao: 'Em Atividade',
    status: 'Ativo',
    membroCipa: 'NÃO',
    ancora: 'NÃO',
    dataAdmissao: '2024-06-14',
    tempoDeCasaDias: 795,
    tempoDeCasaMeses: 26.1,
    faixaTempoCasa: '> 2 anos',
    gestor: 'ALINE CYNTHIA BARBOSA',
  },
  {
    id: 'pes-3244',
    matricula: '3498',
    matriculaDolp: '3498',
    matriculaContratante: 'BR0957677031',
    empresa: 'DOLP ENGENHARIA LTDA - MT',
    nome: 'ADILSON SANTANA MARTINS',
    cargo: 'AUXILIAR DE ALMOXARIFADO',
    tipoFuncao: 'OPERACIONAL',
    filial: 'CUIABÁ - MT',
    departamento: 'OPERACIONAL - CUIABA',
    dataNascimento: '1981-05-07',
    idade: 45,
    naturalidade: 'CUIABA',
    estadoCivil: 'Solteiro(a)',
    cpf: '957.677.031-91',
    rg: '95767703191',
    orgaoExpeditor: 'SSP',
    situacao: 'Em Atividade',
    status: 'Ativo',
    celular: '65981320478',
    membroCipa: 'NÃO',
    ancora: 'NÃO',
    dataAdmissao: '2025-04-01',
    tempoDeCasaDias: 504,
    tempoDeCasaMeses: 16.5,
    faixaTempoCasa: '1 - 2 anos',
    gestor: 'RONILSON FILIPE DO NASCIMENTO',
  },
  {
    id: 'pes-3511',
    matricula: '3726',
    matriculaDolp: '3726',
    matriculaContratante: 'BR0671239022',
    empresa: 'DOLP ENGENHARIA LTDA - MT',
    nome: 'ADISON DE MATOS SOUSA',
    cargo: 'SUPERVISOR',
    tipoFuncao: 'OPERACIONAL',
    filial: 'CUIABÁ - MT',
    departamento: 'OPERACIONAL - CUIABA',
    dataNascimento: '1981-12-22',
    idade: 44,
    naturalidade: 'TARAUACA',
    estadoCivil: 'Solteiro(a)',
    cpf: '671.239.022-20',
    rg: '391542',
    orgaoExpeditor: 'SSP',
    situacao: 'Em Atividade',
    status: 'Ativo',
    celular: '68999176272',
    membroCipa: 'NÃO',
    ancora: 'NÃO',
    dataAdmissao: '2025-07-07',
    tempoDeCasaDias: 407,
    tempoDeCasaMeses: 13.3,
    faixaTempoCasa: '1 - 2 anos',
    gestor: 'DIEFFERSON VITORINO DE MACEDO',
  },
  {
    id: 'pes-3680',
    matricula: '3901',
    matriculaDolp: '3901',
    matriculaContratante: 'BR0013514732',
    empresa: 'DOLP ENGENHARIA LTDA - MT',
    nome: 'ADRIANA ALVES DA SILVA',
    cargo: 'AUXILIAR DE LIMPEZA',
    tipoFuncao: 'OPERACIONAL',
    filial: 'CUIABÁ - MT',
    departamento: 'OPERACIONAL - CUIABA',
    dataNascimento: '1984-08-24',
    idade: 41,
    naturalidade: 'ARIQUEMES',
    estadoCivil: 'Solteiro(a)',
    cpf: '013.514.732-80',
    rg: '01351473280',
    orgaoExpeditor: 'SSP',
    situacao: 'Afastado',
    status: 'Ativo',
    celular: '66999121486',
    membroCipa: 'NÃO',
    ancora: 'NÃO',
    dataAdmissao: '2025-09-08',
    tempoDeCasaDias: 344,
    tempoDeCasaMeses: 11.3,
    faixaTempoCasa: '180 dias - 1 ano',
    gestor: 'JOAO PAULO DA CRUZ PEREIRA',
  },
  {
    id: 'pes-2022',
    matricula: '2448',
    matriculaDolp: '2448',
    matriculaContratante: 'BR737090001',
    empresa: 'DOLP ENGENHARIA LTDA - MT',
    nome: 'ADRIANA GONZAGA DA CRUZ LIMA',
    cargo: 'ELETRICISTA DE REDES DE DISTRIBUIÇÃO',
    tipoFuncao: 'OPERACIONAL',
    filial: 'VÁRZEA GRANDE - MT',
    departamento: 'OPERACIONAL - VARZEA GRANDE',
    dataNascimento: '1987-12-06',
    idade: 38,
    naturalidade: 'CUIABA',
    estadoCivil: 'Casado(a)',
    cpf: '737.090.001-06',
    rg: '17819083',
    orgaoExpeditor: 'SEJSP',
    situacao: 'Afastado',
    status: 'Ativo',
    celular: '65992209388',
    membroCipa: 'NÃO',
    ancora: 'NÃO',
    dataAdmissao: '2024-07-30',
    tempoDeCasaDias: 749,
    tempoDeCasaMeses: 24.6,
    faixaTempoCasa: '> 2 anos',
    gestor: 'CRISTIANO GONCALVES DE OLIVEIRA',
  },
  {
    id: 'pes-2032',
    matricula: '2458',
    matriculaDolp: '2458',
    matriculaContratante: 'BR008641872',
    empresa: 'DOLP ENGENHARIA LTDA - MT',
    nome: 'ADRIANO ROBERTO DE SOUZA AFONSO',
    cargo: 'ELETRICISTA DE REDES DE DISTRIBUIÇÃO',
    tipoFuncao: 'OPERACIONAL',
    filial: 'CUIABÁ - MT',
    departamento: 'OPERACIONAL - CUIABA',
    dataNascimento: '1991-08-22',
    idade: 34,
    naturalidade: 'PORTO VELHO',
    estadoCivil: 'Solteiro(a)',
    cpf: '008.641.872-62',
    rg: '00001096585',
    orgaoExpeditor: 'SESDC',
    situacao: 'Desligado',
    status: 'Desligado',
    celular: '69981215354',
    membroCipa: 'NÃO',
    ancora: 'NÃO',
    dataAdmissao: '2024-08-01',
    dataDemissao: '2024-08-01',
    tempoDeCasaDias: 1,
    tempoDeCasaMeses: 0.1,
    faixaTempoCasa: '< 90 dias (Precoce)',
    tipoDesligamento: 'Término de Experiência',
    motivoSaida: 'Desistência no 1º dia de integração operacional',
    gestor: 'DIEFFERSON VITORINO DE MACEDO',
  },
  {
    id: 'pes-1793',
    matricula: '2221',
    matriculaDolp: '2221',
    matriculaContratante: 'BR067061231',
    empresa: 'DOLP ENGENHARIA LTDA - MT',
    nome: 'ADRIEL DUARTE CARVALHO',
    cargo: 'ELETRICISTA DE REDES DE DISTRIBUIÇÃO',
    tipoFuncao: 'OPERACIONAL',
    filial: 'CUIABÁ - MT',
    departamento: 'OPERACIONAL - CUIABA',
    dataNascimento: '1998-09-25',
    idade: 27,
    naturalidade: 'CORONEL SAPUCAIA',
    estadoCivil: 'Solteiro(a)',
    cpf: '067.061.231-61',
    rg: '26309238',
    orgaoExpeditor: 'SEJSP',
    situacao: 'Afastado',
    status: 'Ativo',
    celular: '65992502687',
    membroCipa: 'NÃO',
    ancora: 'NÃO',
    dataAdmissao: '2024-06-06',
    tempoDeCasaDias: 803,
    tempoDeCasaMeses: 26.4,
    faixaTempoCasa: '> 2 anos',
    gestor: 'THIAGO EDUARDO SIQUEIRA DA SILVA',
  },
  {
    id: 'pes-1983',
    matricula: '2411',
    matriculaDolp: '2411',
    matriculaContratante: 'BR570240491',
    empresa: 'DOLP ENGENHARIA LTDA - MT',
    nome: 'AGNO RODRIGUES DE MORAES',
    cargo: 'ENCARREGADO',
    tipoFuncao: 'OPERACIONAL',
    filial: 'CUIABÁ - MT',
    departamento: 'OPERACIONAL - CUIABA',
    dataNascimento: '1976-03-09',
    idade: 50,
    naturalidade: 'CUIABA',
    estadoCivil: 'Casado(a)',
    cpf: '570.240.491-20',
    rg: '09635424',
    orgaoExpeditor: 'SSP',
    situacao: 'Desligado',
    status: 'Desligado',
    membroCipa: 'NÃO',
    ancora: 'NÃO',
    dataAdmissao: '2024-07-18',
    dataDemissao: '2024-10-08',
    tempoDeCasaDias: 82,
    tempoDeCasaMeses: 2.7,
    faixaTempoCasa: '< 90 dias (Precoce)',
    tipoDesligamento: 'Término de Experiência',
    motivoSaida: 'Não adaptação ao turno noturno e rotas',
    gestor: 'ALINE CYNTHIA BARBOSA',
  },
  {
    id: 'pes-1912',
    matricula: '2339',
    matriculaDolp: '2339',
    matriculaContratante: 'BR976199221',
    empresa: 'DOLP ENGENHARIA LTDA - MT',
    nome: 'AGRIPINO JOSE OJEDA',
    cargo: 'ELETRICISTA DE REDES DE DISTRIBUIÇÃO',
    tipoFuncao: 'OPERACIONAL',
    filial: 'CUIABÁ - MT',
    departamento: 'OPERACIONAL - CUIABA',
    dataNascimento: '1981-10-09',
    idade: 44,
    naturalidade: 'CUIABA',
    estadoCivil: 'Casado(a)',
    cpf: '976.199.221-72',
    rg: '14324067',
    orgaoExpeditor: 'SSP',
    situacao: 'Afastado',
    status: 'Ativo',
    membroCipa: 'NÃO',
    ancora: 'NÃO',
    dataAdmissao: '2024-07-02',
    tempoDeCasaDias: 777,
    tempoDeCasaMeses: 25.5,
    faixaTempoCasa: '> 2 anos',
    gestor: 'ADISON DE MATOS SOUSA',
  },
  {
    id: 'pes-2080',
    matricula: '2499',
    matriculaDolp: '2499',
    matriculaContratante: 'BR405967021',
    empresa: 'DOLP ENGENHARIA LTDA - MT',
    nome: 'AILTON VICENTE DE LIMA',
    cargo: 'SUPERVISOR',
    tipoFuncao: 'OPERACIONAL',
    filial: 'CUIABÁ - MT',
    departamento: 'OPERACIONAL - CUIABA',
    dataNascimento: '1968-09-05',
    idade: 57,
    naturalidade: 'RONDONOPOLIS',
    estadoCivil: 'Casado(a)',
    cpf: '405.967.021-91',
    rg: '06023100',
    orgaoExpeditor: 'SSP',
    situacao: 'Desligado',
    status: 'Desligado',
    membroCipa: 'NÃO',
    ancora: 'NÃO',
    dataAdmissao: '2024-08-07',
    dataDemissao: '2025-05-26',
    tempoDeCasaDias: 292,
    tempoDeCasaMeses: 9.6,
    faixaTempoCasa: '180 dias - 1 ano',
    tipoDesligamento: 'Voluntário (Pedido)',
    motivoSaida: 'Rotas distantes e remuneração variável',
    gestor: 'ALINE CYNTHIA BARBOSA',
  },
  {
    id: 'pes-2065',
    matricula: '2490',
    matriculaDolp: '2490',
    matriculaContratante: 'BR820959571',
    empresa: 'DOLP ENGENHARIA LTDA - MT',
    nome: 'AIRTON JOSE RODRIGUES',
    cargo: 'ENCARREGADO',
    tipoFuncao: 'OPERACIONAL',
    filial: 'CUIABÁ - MT',
    departamento: 'OPERACIONAL - CUIABA',
    dataNascimento: '1977-09-13',
    idade: 48,
    naturalidade: 'ROSARIO OESTE',
    estadoCivil: 'Solteiro(a)',
    cpf: '820.959.571-72',
    rg: '11292113',
    situacao: 'Em Atividade',
    status: 'Ativo',
    celular: '65992298490',
    membroCipa: 'NÃO',
    ancora: 'NÃO',
    dataAdmissao: '2024-08-05',
    tempoDeCasaDias: 743,
    tempoDeCasaMeses: 24.4,
    faixaTempoCasa: '> 2 anos',
    gestor: 'JUCELMO JOSE DA SILVA SANTOS',
  },
  {
    id: 'pes-1870',
    matricula: '2296',
    matriculaDolp: '2296',
    matriculaContratante: 'BR013532822',
    empresa: 'DOLP ENGENHARIA LTDA - MT',
    nome: 'ALDAIR TEIXEIRA NASCIMENTO',
    cargo: 'ELETRICISTA DE REDES DE DISTRIBUIÇÃO',
    tipoFuncao: 'OPERACIONAL',
    filial: 'CUIABÁ - MT',
    departamento: 'OPERACIONAL - CUIABA',
    dataNascimento: '1990-04-11',
    idade: 36,
    naturalidade: 'JURUTI',
    estadoCivil: 'Solteiro(a)',
    cpf: '013.532.822-52',
    rg: '6224462',
    orgaoExpeditor: 'PC',
    situacao: 'Desligado',
    status: 'Desligado',
    membroCipa: 'NÃO',
    ancora: 'NÃO',
    dataAdmissao: '2024-06-24',
    dataDemissao: '2024-10-07',
    tempoDeCasaDias: 105,
    tempoDeCasaMeses: 3.5,
    faixaTempoCasa: '90 - 180 dias',
    tipoDesligamento: 'Involuntário (Empresa)',
    motivoSaida: 'Absenteísmo excessivo e faltas injustificadas',
    gestor: 'MARCOS ANDREY BORGES DA SILVA',
  },
  {
    id: 'pes-1704',
    matricula: '2132',
    matriculaDolp: '2132',
    matriculaContratante: 'BR020277261',
    empresa: 'DOLP ENGENHARIA LTDA - MT',
    nome: 'ALESANDRO DE AVILA FONTES',
    cargo: 'ELETRICISTA DE REDES DE DISTRIBUIÇÃO',
    tipoFuncao: 'OPERACIONAL',
    filial: 'CUIABÁ - MT',
    departamento: 'OPERACIONAL - CUIABA',
    dataNascimento: '1987-03-12',
    idade: 39,
    naturalidade: 'CUIABA',
    estadoCivil: 'Solteiro(a)',
    cpf: '020.277.261-60',
    rg: '16950917',
    orgaoExpeditor: 'SSP',
    situacao: 'Afastado',
    status: 'Ativo',
    celular: '65992097027',
    membroCipa: 'NÃO',
    ancora: 'NÃO',
    dataAdmissao: '2024-05-13',
    tempoDeCasaDias: 827,
    tempoDeCasaMeses: 27.2,
    faixaTempoCasa: '> 2 anos',
    gestor: 'CELSO JUNIOR BARBOZA DE FIGUEIREDO',
  },
  {
    id: 'pes-1739',
    matricula: '2167',
    matriculaDolp: '2167',
    matriculaContratante: 'BR018206931',
    empresa: 'DOLP ENGENHARIA LTDA - MT',
    nome: 'ALESSANDRO APARECIDO CAMPOS DE FRANCA',
    cargo: 'ENCARREGADO LINHA VIVA',
    tipoFuncao: 'OPERACIONAL',
    filial: 'CUIABÁ - MT',
    departamento: 'OPERACIONAL - CUIABA',
    dataNascimento: '1987-01-15',
    idade: 39,
    naturalidade: 'CUIABA',
    estadoCivil: 'Solteiro(a)',
    cpf: '018.206.931-12',
    rg: '18102999',
    orgaoExpeditor: 'SSP',
    situacao: 'Em Atividade',
    status: 'Ativo',
    celular: '65992342455',
    membroCipa: 'NÃO',
    ancora: 'NÃO',
    dataAdmissao: '2024-05-21',
    tempoDeCasaDias: 819,
    tempoDeCasaMeses: 26.9,
    faixaTempoCasa: '> 2 anos',
    gestor: 'ADISON DE MATOS SOUSA',
  },
  {
    id: 'pes-3620',
    matricula: '3820',
    matriculaDolp: '3820',
    matriculaContratante: 'BR0006907061',
    empresa: 'DOLP ENGENHARIA LTDA - MT',
    nome: 'ALESSANDRO NERES SANTOS SOUZA',
    cargo: 'ELETRICISTA DE REDES DE DISTRIBUIÇÃO',
    tipoFuncao: 'OPERACIONAL',
    filial: 'VÁRZEA GRANDE - MT',
    departamento: 'OPERACIONAL - VARZEA GRANDE',
    dataNascimento: '1998-10-06',
    idade: 27,
    naturalidade: 'CUIABA',
    estadoCivil: 'Casado(a)',
    cpf: '006.907.061-03',
    rg: '14448270',
    orgaoExpeditor: 'SSP',
    situacao: 'Desligado',
    status: 'Desligado',
    celular: '65965931400',
    membroCipa: 'NÃO',
    ancora: 'NÃO',
    dataAdmissao: '2025-08-04',
    dataDemissao: '2026-03-27',
    tempoDeCasaDias: 235,
    tempoDeCasaMeses: 7.7,
    faixaTempoCasa: '180 dias - 1 ano',
    tipoDesligamento: 'Voluntário (Pedido)',
    motivoSaida: 'Nova oportunidade no mercado regional',
    gestor: 'MARCOS ANDREY BORGES DA SILVA',
  },
  {
    id: 'pes-2536',
    matricula: '2827',
    matriculaDolp: '2827',
    matriculaContratante: 'BR0016195661',
    empresa: 'DOLP ENGENHARIA LTDA - MT',
    nome: 'ALESSANDRO RAMOS DOS SANTOS',
    cargo: 'ENCARREGADO ITINERANTE',
    tipoFuncao: 'OPERACIONAL',
    filial: 'CUIABÁ - MT',
    departamento: 'DEP. OPERACIONAL - SERVIÇOS',
    dataNascimento: '1988-02-09',
    idade: 38,
    naturalidade: 'ARAGUAPAZ',
    estadoCivil: 'Solteiro(a)',
    cpf: '016.195.661-09',
    rg: '01619566109',
    orgaoExpeditor: 'PC',
    situacao: 'Desligado',
    status: 'Desligado',
    celular: '62991746620',
    membroCipa: 'NÃO',
    ancora: 'NÃO',
    dataAdmissao: '2024-12-11',
    dataDemissao: '2025-02-07',
    tempoDeCasaDias: 58,
    tempoDeCasaMeses: 1.9,
    faixaTempoCasa: '< 90 dias (Precoce)',
    tipoDesligamento: 'Término de Experiência',
    motivoSaida: 'Incompatibilidade de horário com estudos',
    gestor: 'THIAGO EDUARDO SIQUEIRA DA SILVA',
  },
  {
    id: 'pes-1756',
    matricula: '2184',
    matriculaDolp: '2184',
    matriculaContratante: 'BR013117931',
    empresa: 'DOLP ENGENHARIA LTDA - MT',
    nome: 'ALESSANDRO RIOS DO CARMO',
    cargo: 'ELETRICISTA DE REDES DE DISTRIBUIÇÃO',
    tipoFuncao: 'OPERACIONAL',
    filial: 'VÁRZEA GRANDE - MT',
    departamento: 'OPERACIONAL - VARZEA GRANDE',
    dataNascimento: '1987-12-30',
    idade: 38,
    naturalidade: 'CUIABA',
    estadoCivil: 'Solteiro(a)',
    cpf: '013.117.931-43',
    rg: '16969170',
    orgaoExpeditor: 'SSP',
    situacao: 'Em Atividade',
    status: 'Ativo',
    membroCipa: 'NÃO',
    ancora: 'NÃO',
    dataAdmissao: '2024-05-27',
    tempoDeCasaDias: 813,
    tempoDeCasaMeses: 26.7,
    faixaTempoCasa: '> 2 anos',
    gestor: 'JAMERSON HENRIQUE VIANA LIMA SANTOS',
  },
  {
    id: 'pes-2354',
    matricula: '2690',
    matriculaDolp: '2690',
    matriculaContratante: 'BR0704474901',
    empresa: 'DOLP ENGENHARIA LTDA - MT',
    nome: 'ALESSANDRO VIEIRA ROCHA',
    cargo: 'ELETRICISTA DE LINHA VIVA',
    tipoFuncao: 'OPERACIONAL',
    filial: 'CUIABÁ - MT',
    departamento: 'OPERACIONAL',
    dataNascimento: '1996-11-22',
    idade: 29,
    naturalidade: 'FORMOSA',
    estadoCivil: 'Solteiro(a)',
    cpf: '704.474.901-17',
    rg: '6571689',
    orgaoExpeditor: 'SSP',
    situacao: 'Em Atividade',
    status: 'Ativo',
    celular: '6492711203',
    membroCipa: 'NÃO',
    ancora: 'NÃO',
    dataAdmissao: '2024-10-24',
    tempoDeCasaDias: 663,
    tempoDeCasaMeses: 21.8,
    faixaTempoCasa: '1 - 2 anos',
    gestor: 'THIAGO EDUARDO SIQUEIRA DA SILVA',
  },
  {
    id: 'pes-2378',
    matricula: '2712',
    matriculaDolp: '2712',
    matriculaContratante: 'BR841005241',
    empresa: 'DOLP ENGENHARIA LTDA - MT',
    nome: 'ALEX BOM DESPACHO DE ARRUDA BARROS',
    cargo: 'ELETRICISTA DE REDES DE DISTRIBUIÇÃO',
    tipoFuncao: 'OPERACIONAL',
    filial: 'VÁRZEA GRANDE - MT',
    departamento: 'OPERACIONAL - CUIABA',
    dataNascimento: '1977-01-09',
    idade: 49,
    naturalidade: 'CUIABA',
    estadoCivil: 'Solteiro(a)',
    cpf: '841.005.241-53',
    rg: '10839046',
    orgaoExpeditor: 'SSP',
    situacao: 'Desligado',
    status: 'Desligado',
    celular: '65993428094',
    membroCipa: 'NÃO',
    ancora: 'NÃO',
    dataAdmissao: '2024-11-04',
    dataDemissao: '2025-10-22',
    tempoDeCasaDias: 352,
    tempoDeCasaMeses: 11.6,
    faixaTempoCasa: '180 dias - 1 ano',
    tipoDesligamento: 'Voluntário (Pedido)',
    motivoSaida: 'Concorrência com salário superior',
    gestor: 'ALINE CYNTHIA BARBOSA',
  },
  {
    id: 'pes-1706',
    matricula: '2134',
    matriculaDolp: '2134',
    matriculaContratante: 'BR700833801',
    empresa: 'DOLP ENGENHARIA LTDA - MT',
    nome: 'ALEX GLEISON NEVES',
    cargo: 'ELETRICISTA DE REDES DE DISTRIBUIÇÃO',
    tipoFuncao: 'OPERACIONAL',
    filial: 'CUIABÁ - MT',
    departamento: 'OPERACIONAL - CUIABA',
    dataNascimento: '1978-04-29',
    idade: 48,
    naturalidade: 'CUIABA',
    estadoCivil: 'Casado(a)',
    cpf: '700.833.801-59',
    rg: '11151552',
    orgaoExpeditor: 'SSP',
    situacao: 'Desligado',
    status: 'Desligado',
    celular: '65992773168',
    membroCipa: 'NÃO',
    ancora: 'NÃO',
    dataAdmissao: '2024-05-13',
    dataDemissao: '2024-09-11',
    tempoDeCasaDias: 121,
    tempoDeCasaMeses: 4.0,
    faixaTempoCasa: '90 - 180 dias',
    tipoDesligamento: 'Involuntário (Empresa)',
    motivoSaida: 'Erros reincidentes de procedimentos operacionais',
    gestor: 'DIEFFERSON VITORINO DE MACEDO',
  },
  {
    id: 'pes-1879',
    matricula: '2305',
    matriculaDolp: '2305',
    matriculaContratante: 'BR092729633',
    empresa: 'DOLP ENGENHARIA LTDA - MT',
    nome: 'ALEX MIGUEL FURTADO DO NASCIMENTO',
    cargo: 'ELETRICISTA DE REDES DE DISTRIBUIÇÃO',
    tipoFuncao: 'OPERACIONAL',
    filial: 'CUIABÁ - MT',
    departamento: 'OPERACIONAL - CUIABA',
    dataNascimento: '2003-01-14',
    idade: 23,
    naturalidade: 'URUBURETAMA',
    estadoCivil: 'Solteiro(a)',
    cpf: '092.729.633-03',
    rg: '2017237238',
    orgaoExpeditor: 'SSP',
    situacao: 'Desligado',
    status: 'Desligado',
    membroCipa: 'NÃO',
    ancora: 'NÃO',
    dataAdmissao: '2024-06-25',
    dataDemissao: '2025-10-22',
    tempoDeCasaDias: 484,
    tempoDeCasaMeses: 15.9,
    faixaTempoCasa: '1 - 2 anos',
    tipoDesligamento: 'Voluntário (Pedido)',
    motivoSaida: 'Problemas de saúde na família',
    gestor: 'REINALDO FREIRE MARQUES',
  },
  {
    id: 'pes-3436',
    matricula: '3902',
    matriculaDolp: '3902',
    matriculaContratante: 'BR0037645531',
    empresa: 'DOLP ENGENHARIA LTDA - MT',
    nome: 'ALEXANDRE ALVES DE CARVALHO',
    cargo: 'ELETRICISTA DE REDES DE DISTRIBUIÇÃO',
    tipoFuncao: 'OPERACIONAL',
    filial: 'CUIABÁ - MT',
    departamento: 'OPERACIONAL - CUIABA',
    dataNascimento: '1991-08-21',
    idade: 34,
    naturalidade: 'CUIABA',
    estadoCivil: 'União Estável',
    cpf: '037.645.531-46',
    rg: '0629686',
    orgaoExpeditor: 'SSP',
    situacao: 'Desligado',
    status: 'Ativo',
    celular: '6584450734',
    membroCipa: 'NÃO',
    ancora: 'NÃO',
    dataAdmissao: '2025-09-08',
    tempoDeCasaDias: 344,
    tempoDeCasaMeses: 11.3,
    faixaTempoCasa: '180 dias - 1 ano',
    gestor: 'GALBYLENE CRUZ DA SILVA',
  },
  {
    id: 'pes-2019',
    matricula: '2446',
    matriculaDolp: '2446',
    matriculaContratante: 'BR029194481',
    empresa: 'DOLP ENGENHARIA LTDA - MT',
    nome: 'ALEXANDRE GUILHERME DE OLIVEIRA ALVES',
    cargo: 'ELETRICISTA DE REDES DE DISTRIBUIÇÃO',
    tipoFuncao: 'OPERACIONAL',
    filial: 'CUIABÁ - MT',
    departamento: 'OPERACIONAL - CUIABA',
    dataNascimento: '1989-05-30',
    idade: 37,
    naturalidade: 'CUIABA',
    estadoCivil: 'Casado(a)',
    cpf: '029.194.481-70',
    rg: '17704006',
    orgaoExpeditor: 'SSP',
    situacao: 'Desligado',
    status: 'Desligado',
    celular: '65992739735',
    membroCipa: 'NÃO',
    ancora: 'NÃO',
    dataAdmissao: '2024-07-26',
    dataDemissao: '2025-09-22',
    tempoDeCasaDias: 423,
    tempoDeCasaMeses: 13.9,
    faixaTempoCasa: '1 - 2 anos',
    tipoDesligamento: 'Involuntário (Empresa)',
    motivoSaida: 'Faltas reiteradas e baixa produtividade',
    gestor: 'DIEFFERSON VITORINO DE MACEDO',
  },
  {
    id: 'pes-1709',
    matricula: '2137',
    matriculaDolp: '2137',
    matriculaContratante: 'BR727662631',
    empresa: 'DOLP ENGENHARIA LTDA - MT',
    nome: 'ALEXANDRE GUIMARAES DA COSTA',
    cargo: 'ELETRICISTA DE REDES DE DISTRIBUIÇÃO',
    tipoFuncao: 'OPERACIONAL',
    filial: 'CUIABÁ - MT',
    departamento: 'OPERACIONAL - CUIABA',
    dataNascimento: '1985-04-27',
    idade: 41,
    naturalidade: 'CHAPADA DOS GUIMARAES',
    estadoCivil: 'Casado(a)',
    cpf: '727.662.631-87',
    rg: '13751530',
    orgaoExpeditor: 'SSP',
    situacao: 'Desligado',
    status: 'Desligado',
    celular: '65996685968',
    membroCipa: 'NÃO',
    ancora: 'NÃO',
    dataAdmissao: '2024-05-13',
    dataDemissao: '2024-10-24',
    tempoDeCasaDias: 164,
    tempoDeCasaMeses: 5.4,
    faixaTempoCasa: '90 - 180 dias',
    tipoDesligamento: 'Voluntário (Pedido)',
    motivoSaida: 'Dificuldades de deslocamento e transporte',
    gestor: 'ADISON DE MATOS SOUSA',
  },
  {
    id: 'pes-1821',
    matricula: '2248',
    matriculaDolp: '2248',
    matriculaContratante: 'BR059535631',
    empresa: 'DOLP ENGENHARIA LTDA - MT',
    nome: 'ALEXANDRE REIS FONSECA PEREIRA',
    cargo: 'AUXILIAR DE ALMOXARIFADO',
    tipoFuncao: 'OPERACIONAL',
    filial: 'CUIABÁ - MT',
    departamento: 'ADMINISTRATIVO - CUIABA',
    dataNascimento: '1996-01-06',
    idade: 30,
    naturalidade: 'PICOS',
    estadoCivil: 'Solteiro(a)',
    cpf: '059.535.631-16',
    rg: '25891740',
    orgaoExpeditor: 'SSP',
    situacao: 'Desligado',
    status: 'Desligado',
    celular: '65992011156',
    membroCipa: 'NÃO',
    ancora: 'NÃO',
    dataAdmissao: '2024-06-12',
    dataDemissao: '2024-06-18',
    tempoDeCasaDias: 6,
    tempoDeCasaMeses: 0.2,
    faixaTempoCasa: '< 90 dias (Precoce)',
    tipoDesligamento: 'Término de Experiência',
    motivoSaida: 'Desistência no período de treinamento',
    gestor: 'GALBYLENE CRUZ DA SILVA',
  },
  {
    id: 'pes-3928',
    matricula: '4079',
    matriculaDolp: '4079',
    matriculaContratante: 'BR0922694861',
    empresa: 'DOLP ENGENHARIA LTDA - MT',
    nome: 'ALEXSANDER LINDENBERG DIAS DE SA',
    cargo: 'ELETRICISTA DE REDES DE DISTRIBUIÇÃO',
    tipoFuncao: 'OPERACIONAL',
    filial: 'CUIABÁ - MT',
    departamento: 'OPERACIONAL - CUIABA',
    dataNascimento: '1978-01-03',
    idade: 48,
    naturalidade: 'CUIABA',
    estadoCivil: 'Solteiro(a)',
    cpf: '922.694.861-53',
    situacao: 'Desligado',
    status: 'Desligado',
    membroCipa: 'NÃO',
    ancora: 'NÃO',
    dataAdmissao: '2026-01-20',
    dataDemissao: '2026-06-23',
    tempoDeCasaDias: 154,
    tempoDeCasaMeses: 5.1,
    faixaTempoCasa: '90 - 180 dias',
    tipoDesligamento: 'Voluntário (Pedido)',
    motivoSaida: 'Proposta com rotas regionais e benefício habitacional',
    gestor: 'LUCIANO NUNES',
  },
];

export const INITIAL_PONTO_DATA: PontoRecord[] = [
  // Casos Críticos de Faltas/Absenteísmo Cruzados
  {
    id: 'pt-01',
    matricula: 'MT-10442',
    nome: 'Marcos Vinicius de Souza',
    cargo: 'Operador de Empilhadeira',
    filial: 'CUIABÁ - MT',
    periodo: '2026-07',
    faltasInjustificadas: 7,
    faltasJustificadas: 3,
    atestadosDias: 6,
    atrasosMinutos: 240,
    horasFaltaTotal: 62,
    percentualPresenca: 64.8,
  },
  {
    id: 'pt-02',
    matricula: 'MT-10512',
    nome: 'Ronaldo Peixoto de Abreu',
    cargo: 'Operador de Empilhadeira',
    filial: 'CUIABÁ - MT',
    periodo: '2026-07',
    faltasInjustificadas: 9,
    faltasJustificadas: 1,
    atestadosDias: 4,
    atrasosMinutos: 180,
    horasFaltaTotal: 76,
    percentualPresenca: 58.2,
  },
  {
    id: 'pt-03',
    matricula: 'MT-09881',
    nome: 'Luciano Ribeiro Mendes',
    cargo: 'Motorista Carreteiro',
    filial: 'VÁRZEA GRANDE - MT',
    periodo: '2026-07',
    faltasInjustificadas: 5,
    faltasJustificadas: 2,
    atestadosDias: 8,
    atrasosMinutos: 310,
    horasFaltaTotal: 54,
    percentualPresenca: 71.0,
  },
  {
    id: 'pt-04',
    matricula: 'MT-10603',
    nome: 'Juliana Paes Ferreira',
    cargo: 'Auxiliar de Operações Logísticas',
    filial: 'CUIABÁ - MT',
    periodo: '2026-07',
    faltasInjustificadas: 8,
    faltasJustificadas: 0,
    atestadosDias: 5,
    atrasosMinutos: 195,
    horasFaltaTotal: 69,
    percentualPresenca: 61.5,
  },
  {
    id: 'pt-05',
    matricula: 'MT-10332',
    nome: 'Clayton Aparecido Lima',
    cargo: 'Conferente de Carga',
    filial: 'VÁRZEA GRANDE - MT',
    periodo: '2026-07',
    faltasInjustificadas: 6,
    faltasJustificadas: 2,
    atestadosDias: 7,
    atrasosMinutos: 140,
    horasFaltaTotal: 58,
    percentualPresenca: 69.4,
  },
  {
    id: 'pt-06',
    matricula: 'MT-10701',
    nome: 'Everton Silveira Dias',
    cargo: 'Auxiliar de Operações Logísticas',
    filial: 'VÁRZEA GRANDE - MT',
    periodo: '2026-07',
    faltasInjustificadas: 11,
    faltasJustificadas: 1,
    atestadosDias: 3,
    atrasosMinutos: 220,
    horasFaltaTotal: 92,
    percentualPresenca: 51.2,
  },
  {
    id: 'pt-07',
    matricula: 'MT-10499',
    nome: 'Daniel Barreto Costa',
    cargo: 'Operador de Empilhadeira',
    filial: 'VÁRZEA GRANDE - MT',
    periodo: '2026-07',
    faltasInjustificadas: 4,
    faltasJustificadas: 1,
    atestadosDias: 5,
    atrasosMinutos: 90,
    horasFaltaTotal: 38,
    percentualPresenca: 79.5,
  },
  // Colaboradores Ativos com Padrões de Risco
  {
    id: 'pt-08',
    matricula: 'MT-10811',
    nome: 'Gabriel Antunes Prado',
    cargo: 'Auxiliar de Operações Logísticas',
    filial: 'CUIABÁ - MT',
    periodo: '2026-07',
    faltasInjustificadas: 6,
    faltasJustificadas: 1,
    atestadosDias: 4,
    atrasosMinutos: 150,
    horasFaltaTotal: 52,
    percentualPresenca: 72.8,
  },
  {
    id: 'pt-09',
    matricula: 'MT-09941',
    nome: 'Thiago Henrique Santana',
    cargo: 'Operador de Empilhadeira',
    filial: 'CUIABÁ - MT',
    periodo: '2026-07',
    faltasInjustificadas: 1,
    faltasJustificadas: 0,
    atestadosDias: 0,
    atrasosMinutos: 25,
    horasFaltaTotal: 8,
    percentualPresenca: 95.8,
  },
  {
    id: 'pt-10',
    matricula: 'MT-10115',
    nome: 'Bruno Carvalho Moreira',
    cargo: 'Operador de Empilhadeira',
    filial: 'CUIABÁ - MT',
    periodo: '2026-07',
    faltasInjustificadas: 5,
    faltasJustificadas: 2,
    atestadosDias: 3,
    atrasosMinutos: 110,
    horasFaltaTotal: 44,
    percentualPresenca: 78.2,
  },
  {
    id: 'pt-11',
    matricula: 'MT-09554',
    nome: 'André Luiz Brandão',
    cargo: 'Motorista Carreteiro',
    filial: 'VÁRZEA GRANDE - MT',
    periodo: '2026-07',
    faltasInjustificadas: 4,
    faltasJustificadas: 0,
    atestadosDias: 5,
    atrasosMinutos: 80,
    horasFaltaTotal: 36,
    percentualPresenca: 82.0,
  },
  {
    id: 'pt-12',
    matricula: 'MT-10022',
    nome: 'Sérgio Nogueira Campos',
    cargo: 'Conferente de Carga',
    filial: 'VÁRZEA GRANDE - MT',
    periodo: '2026-07',
    faltasInjustificadas: 1,
    faltasJustificadas: 1,
    atestadosDias: 1,
    atrasosMinutos: 40,
    horasFaltaTotal: 12,
    percentualPresenca: 94.0,
  },
  {
    id: 'pt-13',
    matricula: 'MT-10550',
    nome: 'Priscila Vasconcelos',
    cargo: 'Assistente Administrativo de Frota',
    filial: 'CUIABÁ - MT',
    periodo: '2026-07',
    faltasInjustificadas: 0,
    faltasJustificadas: 0,
    atestadosDias: 0,
    atrasosMinutos: 10,
    horasFaltaTotal: 0,
    percentualPresenca: 99.5,
  },
  {
    id: 'pt-14',
    matricula: 'MT-09210',
    nome: 'Fernando Silveira',
    cargo: 'Técnico de Manutenção Mecânica',
    filial: 'CUIABÁ - MT',
    periodo: '2026-07',
    faltasInjustificadas: 3,
    faltasJustificadas: 1,
    atestadosDias: 2,
    atrasosMinutos: 75,
    horasFaltaTotal: 28,
    percentualPresenca: 86.4,
  },
  {
    id: 'pt-15',
    matricula: 'MT-10220',
    nome: 'Aline Correia Duarte',
    cargo: 'Analista de RH',
    filial: 'CUIABÁ - MT',
    periodo: '2026-07',
    faltasInjustificadas: 0,
    faltasJustificadas: 0,
    atestadosDias: 0,
    atrasosMinutos: 0,
    horasFaltaTotal: 0,
    percentualPresenca: 100.0,
  },
  {
    id: 'pt-16',
    matricula: 'MT-10311',
    nome: 'Leandro Barbosa Lima',
    cargo: 'Vendedor Externo',
    filial: 'VÁRZEA GRANDE - MT',
    periodo: '2026-07',
    faltasInjustificadas: 2,
    faltasJustificadas: 0,
    atestadosDias: 1,
    atrasosMinutos: 30,
    horasFaltaTotal: 18,
    percentualPresenca: 91.0,
  },
  {
    id: 'pt-17',
    matricula: 'MT-09740',
    nome: 'Vanessa Rezende',
    cargo: 'Assistente de Faturamento',
    filial: 'CUIABÁ - MT',
    periodo: '2026-07',
    faltasInjustificadas: 0,
    faltasJustificadas: 0,
    atestadosDias: 0,
    atrasosMinutos: 15,
    horasFaltaTotal: 0,
    percentualPresenca: 99.0,
  }
];
